version: '3'
services:

  pipeline:
    container_name: triplexer-pipeline
    image: quay.io/bagnacan/triplexer:latest
    hostname: triplexer
    volumes:
      - .:/data
    depends_on:
      - redis
    links:
      - redis

  redis:
    container_name: triplexer-cache
    image: 'redis:5'
